function money(n){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n)}
function deposit(amount){amount=Number(amount);if(!Number.isFinite(amount)||amount<=0)return notice("Enter a valid amount.");if(player.cash<amount)return notice("Not enough cash.");player.cash-=amount;player.bank.balance+=amount;addTransaction("Cash deposit",amount,"ATM");savePlayer();updateHUD();openATM();notice("Deposit complete.")}
function withdraw(amount){amount=Number(amount);if(!Number.isFinite(amount)||amount<=0)return notice("Enter a valid amount.");if(player.bank.balance<amount)return notice("Insufficient bank funds.");player.bank.balance-=amount;player.cash+=amount;addTransaction("ATM withdrawal",-amount,"ATM");savePlayer();updateHUD();openATM();notice("Withdrawal complete.")}
function transfer(id,amount){amount=Number(amount);const npc=getNPCById(id);if(!npc||!Number.isFinite(amount)||amount<=0)return notice("Check recipient and amount.");if(player.bank.balance<amount)return notice("Insufficient bank funds.");player.bank.balance-=amount;npc.bank.balance+=amount;addTransaction("Transfer to "+npc.name,-amount,"Bank transfer");npc.memory.push("Received a transfer from Darius.");savePlayer();updateHUD();openTransfer();notice("Transfer sent to "+npc.name+".")}
function openATM(){panel(`
<h3>Veyron Bank ATM <button class="close" onclick="closePanel()">×</button></h3>
<div class="row"><span>Cash</span><b class="positive">${money(player.cash)}</b></div>
<div class="row"><span>Bank</span><b>${money(player.bank.balance)}</b></div>
<label>Amount</label><input id="bankAmount" type="number" min="1" placeholder="500">
<button onclick="withdraw(document.getElementById('bankAmount').value)">Withdraw</button>
<button onclick="deposit(document.getElementById('bankAmount').value)">Deposit</button>
<button onclick="openTransactions()">Transactions</button>`)}
function openTransfer(){const opts=getNPCList().map(n=>`<option value="${n.id}">${n.name}</option>`).join("");panel(`<h3>Transfer Money <button class="close" onclick="closePanel()">×</button></h3><label>Recipient</label><select id="recipient">${opts}</select><label>Amount</label><input id="transferAmount" type="number" min="1" placeholder="100"><button onclick="transfer(document.getElementById('recipient').value,document.getElementById('transferAmount').value)">Send Transfer</button>`)}
function openTransactions(){const rows=player.transactions.length?player.transactions.map(t=>`<div class="row"><span>${t.title}<small>${t.info} · ${t.date}</small></span><b class="${t.amount>=0?"positive":"negative"}">${t.amount>=0?"+":""}${money(t.amount)}</b></div>`).join(""):`<p>No transactions yet.</p>`;panel(`<h3>Transaction History <button class="close" onclick="closePanel()">×</button></h3>${rows}`)}
