let canvas,ctx,keys={},world={x:0,y:0},last=0,near=null;
const buildings=[{x:-320,y:-230,w:230,h:160,name:"NORTH HILLS"},{x:80,y:-270,w:300,h:150,name:"VEYRON CENTRAL"},{x:-390,y:50,w:250,h:190,name:"EAST MARKET"},{x:120,y:40,w:330,h:210,name:"IRON DISTRICT"},{x:-100,y:300,w:500,h:130,name:"WEST COAST"},{x:-520,y:-390,w:160,h:100,name:"POLICE HQ"}];
function init(){initializePlayer();canvas=document.getElementById("cityCanvas");ctx=canvas.getContext("2d");resize();addInput();updateHUD();requestAnimationFrame(loop)}
function resize(){const r=canvas.parentElement.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
addEventListener("resize",resize);
function addInput(){addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==="e")interact()});addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);document.querySelectorAll("[data-key]").forEach(b=>{const k=b.dataset.key;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false})}
function loop(t){const dt=Math.min((t-last)/1000||0,.05);last=t;move(dt);draw();requestAnimationFrame(loop)}
function move(dt){const p=currentPlayer();let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);if(!dx&&!dy){p.stamina=Math.min(100,p.stamina+22*dt);return}const sprint=keys.shift&&p.stamina>1,speed=sprint?210:130;if(sprint)p.stamina=Math.max(0,p.stamina-28*dt);else p.stamina=Math.min(100,p.stamina+12*dt);const l=Math.hypot(dx,dy);p.position.x+=dx/l*speed*dt;p.position.y+=dy/l*speed*dt;world.x=p.position.x;world.y=p.position.y;p.location=getDistrict(p.position.x,p.position.y);saveAll();updateHUD()}
function getDistrict(x,y){if(y>250)return"West Coast";if(x<-250&&y<0)return"North Hills";if(x>120&&y>0)return"Iron District";if(x<-250)return"East Market";return"Veyron Central"}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2-world.x,h/2-world.y);ctx.fillStyle="#171d21";ctx.fillRect(-900,-700,1800,1400);ctx.fillStyle="#2a3034";ctx.fillRect(-900,-35,1800,70);ctx.fillRect(-35,-700,70,1400);ctx.fillRect(-900,190,1800,55);ctx.strokeStyle="#697078";ctx.setLineDash([20,18]);ctx.beginPath();ctx.moveTo(-900,0);ctx.lineTo(900,0);ctx.moveTo(0,-700);ctx.lineTo(0,700);ctx.stroke();ctx.setLineDash([]);buildings.forEach(b=>{ctx.fillStyle="#222a31";ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle="#485460";ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle="#84909b";ctx.font="12px Arial";ctx.fillText(b.name,b.x+10,b.y+20)});Object.values(gameState.npcs).forEach(n=>{ctx.beginPath();ctx.fillStyle=n.id.includes("malik")?"#4da3ff":n.id.includes("amara")?"#c77dff":"#f0b35a";ctx.arc(n.position.x,n.position.y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="11px Arial";ctx.fillText(n.name,n.position.x-28,n.position.y-18)});gameState.vehicles.forEach(v=>{ctx.fillStyle=v.owner===gameState.active?"#d6b36a":"#65717d";ctx.fillRect(v.x-16,v.y-9,32,18);ctx.fillStyle="#111";ctx.fillRect(v.x-9,v.y-7,18,6)});const p=currentPlayer();ctx.beginPath();ctx.fillStyle=gameState.active==="darius"?"#42e58c":gameState.active==="malik"?"#4da3ff":"#c77dff";ctx.arc(p.position.x,p.position.y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle="#07110b";ctx.font="bold 10px Arial";ctx.fillText(p.name.split(" ").map(x=>x[0]).join(""),p.position.x-9,p.position.y+4);ctx.restore();updateNearby()}
function updateNearby(){const p=currentPlayer();near=null;let dist=999;Object.values(gameState.npcs).forEach(n=>{const d=Math.hypot(n.position.x-p.position.x,n.position.y-p.position.y);if(d<dist){dist=d;near=n}});const h=document.getElementById("interactHint");if(near&&dist<55){h.textContent=`E / tap: talk to ${near.name}`;h.classList.remove("hidden")}else h.classList.add("hidden")}
function interact(){if(near)talkTo(near.id)}
function talkTo(id){const n=gameState.npcs[id];if(!n)return;const p=currentPlayer();n.trust=Math.min(100,n.trust+1);n.memory.push("Spoke with "+p.name);if(id.includes("malik"))showDialogue(n.name,"“Darius's brother left more questions than answers. Don't trust anyone asking about 404.”");else if(id.includes("amara"))showDialogue(n.name,"“Three protagonists, one investigation. The city reacts differently depending on who is asking.”");else showDialogue(n.name,"“You look like you're searching for something. Veyron notices people who ask too many questions.”");checkMissionProgress();saveAll()}
function showDialogue(name,text){const d=document.getElementById("dialogue");d.innerHTML=`<strong>${name}</strong><p>${text}</p>`;d.classList.remove("hidden");clearTimeout(showDialogue.t);showDialogue.t=setTimeout(()=>d.classList.add("hidden"),5000)}
function updateHUD(){if(!gameState)return;const p=currentPlayer();document.getElementById("cashDisplay").textContent=money(p.cash);document.getElementById("playerName").textContent=p.name;document.getElementById("playerStatus").textContent=p.role+" · "+(p.location||getDistrict(p.position.x,p.position.y));document.getElementById("location").textContent=(p.location||getDistrict(p.position.x,p.position.y)).toUpperCase();document.getElementById("hp").textContent=Math.round(p.health);document.getElementById("stamina").textContent=Math.round(p.stamina);document.getElementById("wanted").textContent=gameState.wanted}
function panel(html){const p=document.getElementById("panel");p.innerHTML=html;p.classList.remove("hidden");p.scrollIntoView({behavior:"smooth",block:"nearest"})}
function closePanel(){document.getElementById("panel").classList.add("hidden")}
function notice(text){const t=document.getElementById("toast");t.textContent=text;t.classList.remove("hidden");clearTimeout(notice.t);notice.t=setTimeout(()=>t.classList.add("hidden"),2300)}
function openPhone(){panel(`<h3>Phone <button class="close" onclick="closePanel()">×</button></h3><div class="row"><span>Messages</span><b>1 new</b></div><div class="row"><span>404 clue</span><b>${gameState.story.clue1?"Found":"Unknown"}</b></div><p>Phone systems are a foundation for calls, messages, photos, emergency reports and later social systems.</p>`)}
function openMap(){panel(`<h3>Veyron City Map <button class="close" onclick="closePanel()">×</button></h3><div class="row"><span>Current</span><b>${currentPlayer().location||"Veyron Central"}</b></div><div class="row"><span>North Hills</span><span>Wealthy / quiet</span></div><div class="row"><span>East Market</span><span>Busy / residential</span></div><div class="row"><span>Iron District</span><span>Industrial / dangerous</span></div><div class="row"><span>West Coast</span><span>Beach / tourist</span></div>`)}
function openNPCs(){panel(`<h3>People <button class="close" onclick="closePanel()">×</button></h3>${Object.values(gameState.npcs).map(n=>`<div class="row"><span><b>${n.name}</b><small>${n.occupation}</small></span><b>Trust ${n.trust}</b></div>`).join("")}`)}
window.addEventListener("load",init);
