/* 404: NO WAY OUT — PHASE 19 BATCH 09 RUNTIME (M81-M88) */
(function(){'use strict';
const IDS=new Set(['M81','M82','M83','M84','M85','M86','M87','M88']);
const SPECS={
M81:{darius:{msg:'Darius is prepared with the final evidence kit.',effect:g=>g.story.m81DariusReady=true},malik:{msg:'Malik is prepared with the final vehicle and tools.',effect:g=>g.story.m81MalikReady=true},amara:{msg:'Amara is prepared with the final evidence channel.',effect:g=>g.story.m81AmaraReady=true},ready:{msg:'All three preparations are locked into one final-operation plan.',effect:g=>{g.story.m81Ready=true;g.story.finalOperationReady=true;}}},
M82:{threats:{msg:'Outstanding threats are identified and resolved.',effect:g=>g.story.m82ThreatsResolved=true},secure:{msg:'People, evidence and the fallback route are secured.',effect:g=>g.story.m82Secured=true},clear:{msg:'No unresolved loose end remains that can compromise the finale.',effect:g=>{g.story.m82Clear=true;g.story.looseEndsCleared=true;}}},
M83:{'route-evidence':{msg:'Evidence-backed routes are compared.',effect:g=>g.story.m83RoutesReviewed=true},'choose-route':{msg:'The safest supported final route is committed.',effect:g=>{g.story.m83RouteChosen=true;g.story.finalRoute=g.story.finalRoute||'supported';}},'reach-site':{msg:'The final site is reached using the committed route.',effect:g=>{g.story.m83SiteReached=true;g.story.finalSiteReached=true;}}},
M84:{'access-ledger':{msg:'Hidden financial records are accessed.',effect:g=>g.story.m84Accessed=true},'secure-ledger':{msg:'The final ledger is secured without destroying the proof.',effect:g=>{g.story.m84Secured=true;g.story.evidence=(+g.story.evidence||0)+2;}},'extract-ledger':{msg:'The final ledger is extracted intact.',effect:g=>{g.story.m84Extracted=true;g.story.finalLedger=true;}}},
M85:{darius:{msg:'Darius reaches the final site and holds his position.',effect:g=>g.story.m85Darius=true},malik:{msg:'Malik secures the extraction route.',effect:g=>g.story.m85Malik=true},amara:{msg:'Amara keeps the evidence channel live.',effect:g=>g.story.m85Amara=true},final:{msg:'The coordinated climax is survived and the operation is completed.',effect:g=>{g.story.m85Final=true;g.story.climaxSurvived=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M86:{commit:{msg:'The selected ending path is confirmed.',effect:g=>{g.story.m86Committed=true;g.story.finalChoiceLocked=true;}},fallback:{msg:'The selected ending has an immediate fallback plan.',effect:g=>g.story.m86FallbackReady=true},ready:{msg:'Final state committed. The aftermath begins.',effect:g=>{g.story.m86Ready=true;g.story.finalStateCommitted=true;}}},
M87:{aftermath:{msg:'The immediate aftermath is survived.',effect:g=>g.story.m87Survived=true},consequences:{msg:'Survivors, evidence and city reaction are recorded.',effect:g=>g.story.m87ConsequencesRecorded=true},leave:{msg:'The chosen ending state is carried into Veyron.',effect:g=>{g.story.m87Left=true;g.story.aftermathComplete=true;}}},
M88:{epilogue:{msg:'The ending-specific epilogue is complete.',effect:g=>g.story.m88Epilogue=true},'world-state':{msg:'Ending-dependent city, relationship and evidence consequences are applied.',effect:g=>applyWorldEnding(g)},'free-roam-unlocked':{msg:'Post-game free roam is unlocked.',effect:g=>{g.story.m88FreeRoam=true;g.story.postgame=true;g.worldState=g.worldState||{};g.worldState.postgame=true;}}}
};
function G(){return window.gameState||null} function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch09=g.p19.batch09||{};g.p19.batch09.missions=g.p19.batch09.missions||{}} function ms(id){ensure();const g=G();return g.p19.batch09.missions[id]||(g.p19.batch09.missions[id]={actions:{},checkpoints:[],completed:false})} function save(){window.saveAll?.()}
function applyWorldEnding(g){const p=g.story?.endingPath;const map={A:'E1',B:'E2',C:'E3',D:'E4'};const eid=map[p]||g.story?.endingId||'E4';g.story.endingId=eid;g.story.endingPath=p||null;g.story.postgame=true;g.worldState=g.worldState||{};g.worldState.ending=eid;g.worldState.endingTitle={E1:'The Escape',E2:'The Crown',E3:'The Sacrifice',E4:'No Way Out'}[eid];g.worldState.districts=g.worldState.districts||{};g.worldState.districts['Veyron Central']=Object.assign({},g.worldState.districts['Veyron Central'],{heat:eid==='E4'?90:25});g.worldState.districts['West Coast']=Object.assign({},g.worldState.districts['West Coast'],{activity:eid==='E2'?'high':'normal'});g.story.finalEndingResolved=eid;}
function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();if(step.kind==='choice')return false;const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}
function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch09.completedAt=g.p19.batch09.completedAt||{};g.p19.batch09.completedAt[id]=Date.now();if(id==='M88')applyWorldEnding(g)}save()}
function selectFinalEnding(path){const g=G();if(!g)return;const map={A:'E1',B:'E2',C:'E3',D:'E4'};if(!map[path])return;g.story=g.story||{};g.story.endingPath=path;g.story.endingId=map[path];g.story.majorChoices=g.story.majorChoices||[];g.story.majorChoices.push('final_'+path);if(path==='A'){g.story.evidence=Math.max(+g.story.evidence||0,8);g.story.exposure=Math.max(+g.story.exposure||0,5);}if(path==='B'){g.story.factionRep=g.story.factionRep||{};g.story.factionRep.control=Math.max(+g.story.factionRep.control||0,65);g.story.exposure=Math.min(+g.story.exposure||0,6);}if(path==='C'){g.story.majorChoices.push('sacrifice');g.story.survivors=Object.assign({darius:true,malik:true,amara:true},g.story.survivors||{});g.story.survivors.malik=false;}if(path==='D'){g.story.exposure=Math.max(+g.story.exposure||0,8);g.story.evidence=Math.min(+g.story.evidence||0,7);}g.story.finalChoiceLocked=true;save();window.closePanel?.();window.phase19Advance?.();window.notice?.('Final ending locked: '+map[path]);}
function selectFinalRoute(route){const g=G();if(!g||!['supported','alternate'].includes(route))return;g.story=g.story||{};g.story.finalRoute=route;g.story.finalRouteLocked=true;save();window.closePanel?.();window.phase19Advance?.();window.notice?.('Final route locked: '+route);}function openRouteChoice(){window.panel?.(`<div class="mission-result"><small>M83 — THE FINAL ROUTE</small><h2>Choose the final route.</h2><p>Commit the route supported by the evidence or take the alternate approach.</p><div class="choice-grid"><button onclick="phase19Batch09SelectRoute('supported')">SUPPORTED ROUTE</button><button onclick="phase19Batch09SelectRoute('alternate')">ALTERNATE ROUTE</button></div></div>`);}
function openEndingChoice(){window.panel?.('<div class="mission-result"><small>M86 — THE LAST CHOICE</small><h2>Choose the ending.</h2><p>The four authoritative endings remain distinct. Your selection becomes persistent.</p><div class="choice-grid"><button onclick="phase19Batch09SelectEnding(\'A\')">E1 · THE ESCAPE</button><button onclick="phase19Batch09SelectEnding(\'B\')">E2 · THE CROWN</button><button onclick="phase19Batch09SelectEnding(\'C\')">E3 · THE SACRIFICE</button><button onclick="phase19Batch09SelectEnding(\'D\')">E4 · NO WAY OUT</button></div></div>');}
function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}
function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 09 QA <button class="close" onclick="closePanel()">×</button></h3><p>M81-M88 final campaign acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;h+=`<div class="row"><span>Ending</span><b>${G()?.story?.endingId||'UNRESOLVED'}</b></div>`;window.panel?.(h)}
window.phase19Batch09SelectEnding=selectFinalEnding;window.phase19Batch09SelectRoute=selectFinalRoute;window.phase19Batch09Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA,openEndingChoice,selectFinalEnding,openRouteChoice,selectFinalRoute};function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch09.complete){g.p19.batch09.complete=true;g.p19.batch09.completedAt=Date.now();g.story=g.story||{};g.story.campaign88BrowserComplete=true;save();window.notice?.('BATCH 09 COMPLETE · M81-M88 final campaign gate passed.')}}setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch09QAButton')){const b=document.createElement('button');b.id='phase19Batch09QAButton';b.textContent='BATCH 09 QA';b.onclick=openQA;q.appendChild(b)}},2600));})();
