/* 404: NO WAY OUT — PHASE 19 BATCH 04 RUNTIME (M31-M40) */
(function(){'use strict';
const IDS=new Set(Array.from({length:10},(_,i)=>`M${String(i+31).padStart(2,'0')}`));
const SPECS={
 M31:{'evidence-chain':{msg:'The 404 evidence chain is assembled.',effect:g=>g.story.m31EvidenceChain=true},'cross-check':{msg:'The three known threads align with the 404 evidence chain.',effect:g=>g.story.m31CrossChecked=true},confirm:{msg:'404 is no longer just a label. The operation has a shape and a purpose.',effect:g=>{g.story.m31Confirmed=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
 M32:{'review-paths':{msg:'Every recipient carries a different risk.',effect:g=>g.story.m32PathsReviewed=true},'commit-choice':{msg:'The ending path is committed. That choice is now persistent.',effect:g=>{g.story.m32ChoiceCommitted=true;g.story.endingPath=g.story.endingPath||'pending_commit';}},'secure-choice':{msg:'Choice secured. The remaining missions will respect it.',effect:g=>{g.story.m32ChoiceSecured=true;g.story.consequenceLock=true;}}},
 M33:{'stage-operation':{msg:'The operation is staged. No more room for improvisation.',effect:g=>g.story.m33OperationStaged=true},execute:{msg:'The chosen operation is underway.',effect:g=>{g.story.m33Executed=true;g.story.policePressure=(+g.story.policePressure||0)+1;}},survive:{msg:'Operation survived. The result is preserved.',effect:g=>{g.story.m33Survived=true;g.story.evidence=(+g.story.evidence||0)+1;g.wanted=Math.max(0,+g.wanted||0);}}},
 M34:{assess:{msg:'The city is still carrying the consequences.',effect:g=>g.story.m34Assessed=true},epilogue:{msg:'Epilogue conditions satisfied for the selected path.',effect:g=>g.story.m34Epilogue=true},'leave-mark':{msg:'The final world-state marker has been persisted.',effect:g=>{g.story.m34WorldStateLocked=true;g.story.finalConsequenceState=true;}}},
 M35:{'find-signal':{msg:'Coded signal located in East Market.',effect:g=>g.story.m35SignalFound=true},'track-exchange':{msg:'Buyer and seller tracked without losing the exchange.',effect:g=>g.story.m35ExchangeTracked=true},identify:{msg:'Signal, buyer and seller are identified. Evidence preserved.',effect:g=>{g.story.m35Identified=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
 M36:{position:{msg:'Observation position established under the rain cover.',effect:g=>g.story.m36Positioned=true},record:{msg:'Protected meeting recorded.',effect:g=>{g.story.m36Recorded=true;g.story.evidence=(+g.story.evidence||0)+1;}},'leave-district':{msg:'Observation complete. Malik clears Central without exposing the team.',effect:g=>{g.story.m36LeftClean=true;g.story.exposure=Math.max(0,(+g.story.exposure||0)-1);}}},
 M37:{'meet-contact':{msg:'The North Hills contact agreed to talk.',effect:g=>g.story.m37ContactMet=true},'earn-cooperation':{msg:'Cooperation earned. The contact is willing to share the address.',effect:g=>{g.story.m37Cooperation=true;}},'obtain-address':{msg:'Address obtained and protected.',effect:g=>{g.story.m37Address=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
 M38:{'compare-shipment':{msg:'Shipment and manifest are being compared line by line.',effect:g=>g.story.m38Compared=true},'find-mismatch':{msg:'A shipment number does not match the manifest.',effect:g=>g.story.m38Mismatch=true},photograph:{msg:'Relevant manifest page photographed and preserved.',effect:g=>{g.story.m38Photographed=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
 M39:{'pick-passenger':{msg:'Passenger identified. Malik has the tail.',effect:g=>g.story.m39PassengerPicked=true},'track-network':{msg:'Passenger tracked through the airport network.',effect:g=>g.story.m39NetworkTracked=true},destination:{msg:'Destination identified. The airport trail points beyond Veyron.',effect:g=>{g.story.m39Destination=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
 M40:{'investigate-rumor':{msg:'The first Blackwater Island rumor has a physical lead.',effect:g=>g.story.m40RumorInvestigated=true},verify:{msg:'Rumor verified against evidence on the island.',effect:g=>g.story.m40Verified=true},'return-proof':{msg:'Proof recovered and the island lead preserved.',effect:g=>{g.story.m40Proof=true;g.story.evidence=(+g.story.evidence||0)+1;g.story.blackwaterLead=true;}}}
};
function G(){return window.gameState||null}function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch04=g.p19.batch04||{};g.p19.batch04.missions=g.p19.batch04.missions||{};}
function ms(id){ensure();const g=G();return g.p19.batch04.missions[id]||(g.p19.batch04.missions[id]={actions:{},checkpoints:[],completed:false});}function save(){window.saveAll?.()}
function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}
function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch04.completedAt=g.p19.batch04.completedAt||{};g.p19.batch04.completedAt[id]=Date.now()}save()}
function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}
function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}
function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 04 QA <button class="close" onclick="closePanel()">×</button></h3><p>M31-M40 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch04Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};
function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch04.complete){g.p19.batch04.complete=true;g.p19.batch04.completedAt=Date.now();save();window.notice?.('BATCH 04 COMPLETE · M31-M40 production gate passed.')}}
setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch04QAButton')){const b=document.createElement('button');b.id='phase19Batch04QAButton';b.textContent='BATCH 04 QA';b.onclick=openQA;q.appendChild(b)}},2000));})();
