/* 404: NO WAY OUT — PHASE 19 BATCH 08 RUNTIME (M71-M80) */
(function(){'use strict';
const IDS=new Set(["M71", "M72", "M73", "M74", "M75", "M76", "M77", "M78", "M79", "M80"]);
const SPECS={
M71:{"review-ledger":{msg:"Cash-flow ledger reviewed; the pressure points are visible.",effect:g=>{g.story.m71Reviewed=true}},"stabilize-costs":{msg:"Major cost pressure stabilized without breaking operations.",effect:g=>{g.story.m71Stabilized=true}},"lock-cashflow":{msg:"Positive cash flow locked for the operation.",effect:g=>{g.story.m71Positive=true;g.story.cashFlowPositive=true;g.money=(+g.money||0)+750}}},
M72:{"trace-introduction":{msg:"The quiet introduction traces back to a protected investor channel.",effect:g=>{g.story.m72Traced=true}},"meet-investor":{msg:"Investor contact made without exposing the operation.",effect:g=>{g.story.m72Met=true}},"secure-condition":{msg:"Conditional investment secured with terms recorded.",effect:g=>{g.story.m72Secured=true;g.story.investorAccess=true;g.money=(+g.money||0)+1250}}},
M73:{"flag-transactions":{msg:"Every flagged transaction is catalogued.",effect:g=>{g.story.m73Flagged=true}},"reconcile-records":{msg:"Conflicting entries reconciled and the useful trail preserved.",effect:g=>{g.story.m73Reconciled=true;g.story.evidence=(+g.story.evidence||0)+1}},"close-audit":{msg:"The audit closes with every flagged transaction resolved.",effect:g=>{g.story.m73Closed=true;g.story.businessRecordsClean=true}}},
M74:{"inspect-photo":{msg:"The photograph yields a distinctive location clue.",effect:g=>{g.story.m74PhotoRead=true}},"match-location":{msg:"The old photograph matches a real Veyron location.",effect:g=>{g.story.m74Matched=true}},"recover-item":{msg:"The hidden item is recovered from the matching location.",effect:g=>{g.story.m74Recovered=true;g.story.evidence=(+g.story.evidence||0)+1;g.story.brotherTrail=true}}},
M75:{"decode-message":{msg:"The message decodes into a usable meeting instruction.",effect:g=>{g.story.m75Decoded=true}},"verify-marker":{msg:"The meeting marker checks out; the route is genuine.",effect:g=>{g.story.m75Verified=true}},"reach-meeting":{msg:"Meeting point reached with the decoded message intact.",effect:g=>{g.story.m75Meeting=true;g.story.evidence=(+g.story.evidence||0)+1}}},
M76:{"reconnect-contact":{msg:"The old contact agrees to talk again.",effect:g=>{g.story.m76Reconnected=true}},"ask-missing-detail":{msg:"The missing detail is recovered without escalating the contact.",effect:g=>{g.story.m76Detail=true;g.story.evidence=(+g.story.evidence||0)+1}},"protect-contact":{msg:"The contact remains protected and available for the next lead.",effect:g=>{g.story.m76Protected=true;g.story.relationshipPreserved=true}}},
M77:{"survey-business":{msg:"The legitimate business hides structural evidence of a second space.",effect:g=>{g.story.m77Surveyed=true}},"find-hidden-entry":{msg:"The concealed entry beneath the business is located.",effect:g=>{g.story.m77Entry=true}},"recover-archive":{msg:"Archive recovered and the hidden room left secure.",effect:g=>{g.story.m77Archive=true;g.story.evidence=(+g.story.evidence||0)+1;g.story.archiveRecovered=true}}},
M78:{"sort-evidence":{msg:"Disconnected evidence is sorted into usable groups.",effect:g=>{g.story.m78Sorted=true}},"connect-nodes":{msg:"Required evidence nodes are connected into one network.",effect:g=>{g.story.m78Connected=true;g.story.evidence=(+g.story.evidence||0)+1}},"lock-network-map":{msg:"Network map locked with the required connections intact.",effect:g=>{g.story.m78Locked=true;g.story.networkMapped=true}}},
M79:{"find-first-confirmation":{msg:"First independent confirmation obtained.",effect:g=>{g.story.m79First=true;g.story.evidence=(+g.story.evidence||0)+1}},"find-second-confirmation":{msg:"Second independent confirmation obtained without exposing the source.",effect:g=>{g.story.m79Second=true;g.story.evidence=(+g.story.evidence||0)+1}},"identify-director":{msg:"Two independent confirmations identify the person directing the operation.",effect:g=>{g.story.m79Director=true;g.story.directorIdentified=true}}},
M80:{"review-relationship":{msg:"Relationship state reviewed before the confrontation.",effect:g=>{g.story.m80Reviewed=true}},"confront-teammate":{msg:"The hidden decision is confronted directly.",effect:g=>{g.story.m80Confronted=true}},"resolve-trust-path":{msg:"The confrontation resolves along the established relationship path.",effect:g=>{g.story.m80Resolved=true;g.story.trustConfrontationResolved=true}}},
};
function G(){return window.gameState||null}function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch08=g.p19.batch08||{};g.p19.batch08.missions=g.p19.batch08.missions||{}}function ms(id){ensure();const g=G();return g.p19.batch08.missions[id]||(g.p19.batch08.missions[id]={actions:{},checkpoints:[],completed:false})}function save(){window.saveAll?.()}function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch08.completedAt=g.p19.batch08.completedAt||{};g.p19.batch08.completedAt[id]=Date.now()}save()}function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 08 QA <button class="close" onclick="closePanel()">×</button></h3><p>M71-M80 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch08Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch08.complete){g.p19.batch08.complete=true;g.p19.batch08.completedAt=Date.now();save();window.notice?.('BATCH 08 COMPLETE · M71-M80 production gate passed.')}}setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch08QAButton')){const b=document.createElement('button');b.id='phase19Batch08QAButton';b.textContent='BATCH 08 QA';b.onclick=openQA;q.appendChild(b)}},2000));})();
