/* 404: NO WAY OUT — PHASE 19 BATCH 02 RUNTIME (M11-M20)
 * Mission-specific prototype logic layered over the canonical 2D mission engine.
 * This is an implementation/data contract, not a claim of finished Unreal production.
 */
(function(){'use strict';
const IDS=new Set(Array.from({length:10},(_,i)=>`M${String(i+11).padStart(2,'0')}`));
const SPECS={
 M11:{steps:{'witness-file':{msg:'Witness record located.',state:{witnessLocated:true}},'witness-contact':{msg:'Witness contact point found.',state:{witnessContacted:true}},'witness-convince':{msg:'Witness agrees to speak. Evidence chain strengthened.',effect:g=>{g.story.evidence=(Number(g.story.evidence)||0)+1;g.story.witnessCooperating=true;trust(g,'amara','darius',2);}}}},
 M12:{steps:{'route-clear':{msg:'A low-visibility route is clear.',state:{safeRouteFound:true}},'escort-witness':{msg:'Witness moved without identification.',effect:g=>{g.story.witnessEscorted=true;}} ,'safehouse':{msg:'Witness delivered to safety.',effect:g=>{g.story.witnessSafe=true;g.story.exposure=Math.max(0,(Number(g.story.exposure)||0)-1);trust(g,'malik','darius',2);}}}},
 M13:{steps:{'vehicle-source':{msg:'Workshop vehicle inspected. It is usable.',effect:g=>{g.story.vehicleCandidateInspected=true;}},'vehicle-store':{msg:'Vehicle acquired and stored at Reed Workshop.',effect:g=>{g.story.workshopVehicleOwned=true;const p=g.characters?.malik||g.characters?.[g.active];const v=(g.vehicles||[]).find(v=>v.id==='workshop_getaway_01')||{id:'workshop_getaway_01',name:'Reed Workshop Runner',type:'Car',owner:'malik',x:410,y:150,health:100,owned:true};v.owner='malik';v.owned=true;v.storedAt='workshop';v.health=100;v.tires=[1,2,3,4].map(()=>({state:'healthy',pressure:100}));g.vehicles=g.vehicles||[];if(!g.vehicles.includes(v))g.vehicles.push(v);if(p)p.reputation=(p.reputation||0)+1;trust(g,'malik','darius',2);}}}},
 M14:{steps:{'damage-check':{msg:'Front tire damage confirmed.',effect:g=>{g.story.tireFailureDetected=true;const v=findVehicle(g);if(v){v.tires=v.tires||[];if(!v.tires.length)v.tires=[1,2,3,4].map(()=>({state:'healthy',pressure:100}));v.tires[0]={state:'popped',pressure:0};v.handlingPenalty=0.25;}}},'repair-tire':{msg:'Tire repaired/replaced. Handling restored.',effect:g=>{const v=findVehicle(g);if(v){v.tires=(v.tires||[1,2,3,4]).map(()=>({state:'healthy',pressure:100}));v.handlingPenalty=0;}g.story.tireRepaired=true;}},'destination':{msg:'Destination reached before the situation escalated.',effect:g=>{g.story.vehicleRecoveryComplete=true;trust(g,'malik','darius',1);}}}},
 M15:{steps:{'package-secure':{msg:'Evidence package secured. Delivery clock is running.',effect:g=>{g.story.packageSecured=true;g.p19.batch02.missions.M15.deliveryStartedAt=performance.now();}},'package-deliver':{msg:'Package delivered. Evidence chain preserved.',effect:g=>{const x=g.p19.batch02.missions.M15;const elapsed=((performance.now()-(x.deliveryStartedAt||performance.now()))/1000);x.deliverySeconds=Math.round(elapsed);x.deliveryOnTime=elapsed<=120;g.story.packageDelivered=true;if(!x.deliveryOnTime)g.story.packageLate=true;else g.story.evidence=(Number(g.story.evidence)||0)+1;}}}},
 M16:{steps:{'target-identify':{msg:'Target driver identified from the network.',effect:g=>{g.story.driverIdentified=true;g.story.driverIdentityEvidence=true;}},'tail-start':{msg:'Tail established. Keep distance and avoid identification.',effect:g=>{g.story.tailStarted=true;}},'tail-finish':{msg:'Target followed without losing them. Route data captured.',effect:g=>{g.story.tailComplete=true;g.story.evidence=(Number(g.story.evidence)||0)+1;trust(g,'amara','darius',2);}}}},
 M17:{steps:{'incident':{msg:'Witness incident contained.',effect:g=>{g.story.witnessIncidentResolved=true;}},'search-break':{msg:'Active search pattern broken.',effect:g=>{g.story.searchBroken=true;g.story.policePressure=Math.max(0,(Number(g.story.policePressure)||0)-1);}},'escape':{msg:'Search area escaped. The witness system is now a real threat.',effect:g=>{g.story.searchEscaped=true;g.story.exposure=(Number(g.story.exposure)||0)+1;trust(g,'malik','darius',1);trust(g,'amara','darius',1);}}}},
 M18:{steps:{'pursuit':{msg:'Police pursuit active. Keep moving.',effect:g=>{g.story.pursuitActive=true;g.story.policePressure=(Number(g.story.policePressure)||0)+1;}},'break-line':{msg:'Line of sight broken. Search radius is shrinking.',effect:g=>{g.story.lineOfSightBroken=true;g.story.policePressure=Math.max(0,(Number(g.story.policePressure)||0)-1);}},'safe-location':{msg:'Safe location reached. Pursuit lost.',effect:g=>{g.story.pursuitActive=false;g.story.heatEscaped=true;g.wanted=Math.max(0,(Number(g.wanted)||0)-1);trust(g,'malik','darius',1);}}}},
 M19:{steps:{'warehouse-entry':{msg:'Warehouse 7 entered. Ledger location confirmed.',effect:g=>{g.story.warehouseEntered=true;}},'ledger-secure':{msg:'Hidden ledger secured intact.',effect:g=>{g.story.ledgerSecured=true;g.story.evidence=(Number(g.story.evidence)||0)+1;}},'warehouse-exit':{msg:'Port escaped with the ledger intact.',effect:g=>{g.story.ledgerEscaped=true;g.story.policePressure=(Number(g.story.policePressure)||0)+1;trust(g,'amara','darius',1);}}}},
 M20:{steps:{'wanted-lower':{msg:'Wanted level reduced. The city is watching less closely.',effect:g=>{g.wanted=Math.max(0,(Number(g.wanted)||0)-1);g.story.wantedLowered=true;}},'evidence-track':{msg:'Lost evidence traced through the Central route.',effect:g=>{g.story.lostEvidenceTracked=true;}},'evidence-recover':{msg:'Lost evidence recovered. Exposure consequences are contained.',effect:g=>{g.story.lostEvidenceRecovered=true;g.story.evidence=(Number(g.story.evidence)||0)+1;g.story.exposure=Math.max(0,(Number(g.story.exposure)||0)-1);trust(g,'malik','darius',1);trust(g,'amara','darius',1);}}}}
};
function state(){return window.gameState||null} function ensure(){const g=state();if(!g)return;g.p19=g.p19||{};g.p19.batch02=g.p19.batch02||{};g.p19.batch02.missions=g.p19.batch02.missions||{};g.p19.batch02.qa=g.p19.batch02.qa||{};}
function ms(id){ensure();const g=state();return g.p19.batch02.missions[id]||(g.p19.batch02.missions[id]={actions:{},checkpoints:[],completed:false});}
function save(){window.saveAll?.()} function trust(g,a,b,n){g.p18?.relationships?.[a]?.[b]&&(g.p18.relationships[a][b].trust=Math.min(100,(g.p18.relationships[a][b].trust||0)+n));}
function findVehicle(g){return (g.vehicles||[]).find(v=>v.id==='workshop_getaway_01')||(g.vehicles||[]).find(v=>v.owner==='malik');}
function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.steps?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});if(spec.state)Object.assign(x,spec.state);spec.effect?.(state());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true;}
function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(state()?.wanted||0)===0;x.optional=x.clean?20:0;if(x.completed){state().p19.batch02.completedAt=state().p19.batch02.completedAt||{};state().p19.batch02.completedAt[id]=Date.now();}save();}
function qaSnapshot(){ensure();const g=state();const out={};IDS.forEach(id=>{const x=ms(id);const r=g.missionRuntime?.results?.[id];out[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null};});return out;}
function batchComplete(){return [...IDS].every(id=>!!state()?.missionRuntime?.results?.[id]&&!state().missionRuntime.results[id].failed)}
function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 02 QA <button class="close" onclick="closePanel()">×</button></h3><p>M11-M20 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch02Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};
function observe(){const g=state();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch02.complete){g.p19.batch02.complete=true;g.p19.batch02.completedAt=Date.now();save();window.notice?.('BATCH 02 COMPLETE · M11-M20 production gate passed.')}}
setInterval(observe,500);
window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch02QAButton')){const b=document.createElement('button');b.id='phase19Batch02QAButton';b.textContent='BATCH 02 QA';b.onclick=openQA;q.appendChild(b)}},1900));
})();
