/* 404: NO WAY OUT — PHASE 19 BATCH 06 RUNTIME (M51-M60) */
(function(){'use strict';
const IDS=new Set(['M51', 'M52', 'M53', 'M54', 'M55', 'M56', 'M57', 'M58', 'M59', 'M60']);const SPECS={
M51:{"follow-response":{msg:"Emergency response located; Malik is behind the route.",effect:g=>{g.story.m51ResponseRoute=true}},"hold-route":{msg:"Route maintained without losing the response.",effect:g=>{g.story.m51RouteHeld=true}},"reach-destination":{msg:"Destination reached before the emergency route ends.",effect:g=>{g.story.m51Arrived=true}}},
M52:{"trace-vehicle":{msg:"The stolen vehicle trail is traced from the workshop lead.",effect:g=>{g.story.m52Trail=true}},"recover-vehicle":{msg:"Stolen vehicle recovered without destroying the recovery trail.",effect:g=>{g.story.m52Recovered=true}},"return-intact":{msg:"Vehicle returned intact to Reed Workshop.",effect:g=>{g.story.m52Returned=true;g.story.vehicleRecoveryCount=(+g.story.vehicleRecoveryCount||0)+1}}},
M53:{"reach-contact":{msg:"Contact reached before the assault can escalate.",effect:g=>{g.story.m53ContactReached=true}},"protect-contact":{msg:"Contact protected through the encounter.",effect:g=>{g.story.m53Protected=true}},"survive-encounter":{msg:"Encounter survived and contact is clear.",effect:g=>{g.story.m53Survived=true;g.story.evidence=(+g.story.evidence||0)+1}}},
M54:{"trigger-pursuit":{msg:"Two-unit police pursuit triggered.",effect:g=>{g.story.m54PursuitStarted=true;g.policeHeat=Math.max(+g.policeHeat||0,2);g.wanted=Math.max(+g.wanted||0,2)}},"lose-first-unit":{msg:"First police unit lost without incapacitation.",effect:g=>{g.story.m54FirstUnitLost=true}},"clear-search":{msg:"Both units lost and the search is clear.",effect:g=>{g.story.m54SearchClear=true;g.wanted=Math.max(0,(+g.wanted||0)-2);g.policeHeat=Math.max(0,(+g.policeHeat||0)-2)}}},
M55:{"locate-record":{msg:"The evidence record is located before destruction.",effect:g=>{g.story.m55RecordLocated=true}},"secure-record":{msg:"Record secured and preserved.",effect:g=>{g.story.m55RecordSecured=true;g.story.evidence=(+g.story.evidence||0)+1}},"leave-territory":{msg:"Police territory cleared with the record intact.",effect:g=>{g.story.m55LeftTerritory=true}}},
M56:{"reach-witness":{msg:"Witness reached before the exposure team.",effect:g=>{g.story.m56WitnessReached=true}},"escort-witness":{msg:"Witness escorted away from the threat.",effect:g=>{g.story.m56Escorted=true}},"safe-exit":{msg:"Witness reaches a safe exit.",effect:g=>{g.story.m56Safe=true;g.story.witnessProtected=true}}},
M57:{"trigger-response":{msg:"Maximum-level response triggered.",effect:g=>{g.story.m57MaxResponse=true;g.wanted=Math.max(+g.wanted||0,5);g.policeHeat=Math.max(+g.policeHeat||0,5)}},"evade-response":{msg:"Maximum response broken without incapacitation.",effect:g=>{g.story.m57Evaded=true}},"reach-safehouse":{msg:"Designated safehouse reached and response cleared.",effect:g=>{g.story.m57Safehouse=true;g.wanted=0;g.policeHeat=0}}},
M58:{"detect-tail":{msg:"The surveillance tail is detected without direct confrontation.",effect:g=>{g.story.m58TailDetected=true}},"identify-tail":{msg:"Tail identity and pattern are confirmed.",effect:g=>{g.story.m58TailIdentified=true;g.story.evidence=(+g.story.evidence||0)+1}},"break-surveillance":{msg:"Surveillance is broken and the team is no longer being followed.",effect:g=>{g.story.m58Broken=true;g.story.exposure=Math.max(0,(+g.story.exposure||0)-1)}}},
M59:{"assess-risk":{msg:"Cleanest resolution path selected.",effect:g=>{g.story.m59RiskAssessed=true}},"resolve-cleanly":{msg:"Objective resolved without escalating the situation.",effect:g=>{g.story.m59Resolved=true}},"confirm-no-wanted":{msg:"No new wanted points were added.",effect:g=>{g.story.m59Clean=true;g.story.m59WantedAtStart=Number(g.wanted||0)}}},
M60:{"meet-broker":{msg:"Broker meeting established without exposing the team.",effect:g=>{g.story.m60BrokerMet=true}},"negotiate-access":{msg:"Terms accepted for restricted network access.",effect:g=>{g.story.m60Negotiated=true}},"obtain-token":{msg:"Access token obtained and secured.",effect:g=>{g.story.m60Token=true;g.story.evidence=(+g.story.evidence||0)+1;g.story.networkAccess=true}}},
};function G(){return window.gameState||null}function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch06=g.p19.batch06||{};g.p19.batch06.missions=g.p19.batch06.missions||{}}function ms(id){ensure();const g=G();return g.p19.batch06.missions[id]||(g.p19.batch06.missions[id]={actions:{},checkpoints:[],completed:false})}function save(){window.saveAll?.()}function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch06.completedAt=g.p19.batch06.completedAt||{};g.p19.batch06.completedAt[id]=Date.now()}save()}function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 06 QA <button class="close" onclick="closePanel()">×</button></h3><p>M51-M60 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}window.phase19Batch06Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch06.complete){g.p19.batch06.complete=true;g.p19.batch06.completedAt=Date.now();save();window.notice?.('BATCH 06 COMPLETE · M51-M60 production gate passed.')}}setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch06QAButton')){const b=document.createElement('button');b.id='phase19Batch06QAButton';b.textContent='BATCH 06 QA';b.onclick=openQA;q.appendChild(b)}},2000));})();
