/* 404: NO WAY OUT — PHASE 19 BATCH 03 RUNTIME (M21-M30)
 * Mission-specific gameplay contracts layered over the canonical 2D mission engine.
 * This is prototype implementation plus Unreal-ready state contracts, not final 3D production.
 */
(function(){'use strict';
const IDS=new Set(Array.from({length:10},(_,i)=>`M${String(i+21).padStart(2,'0')}`));
const SPECS={
 M21:{steps:{darius:{msg:'Darius has the first angle: the Central lead is confirmed.',effect:g=>g.story.m21DariusAngle=true},malik:{msg:'Malik has the vehicle angle. The workshop route is confirmed.',effect:g=>g.story.m21MalikAngle=true},amara:{msg:'Amara has the information angle. The three threads now intersect.',effect:g=>g.story.m21AmaraAngle=true},converge:{msg:'Three angles, one lead. The team has a direction.',effect:g=>{g.story.m21Converged=true;g.story.evidence=(Number(g.story.evidence)||0)+1;trust(g,'malik','darius',1);trust(g,'amara','darius',1);}}}},
 M22:{steps:{'decoy-prepare':{msg:'Decoy prepared. The real package remains protected.',effect:g=>g.story.decoyPrepared=true},'decoy-deliver':{msg:'Decoy delivered. The network is moving toward the false package.',effect:g=>{g.story.decoyDelivered=true;g.story.realPackageProtected=true;}},confirm:{msg:'Diversion confirmed. The real package stayed out of sight.',effect:g=>{g.story.decoyConfirmed=true;g.story.exposure=Math.max(0,(Number(g.story.exposure)||0)-1);trust(g,'amara','darius',2);}}}},
 M23:{steps:{'target-locate':{msg:'Fleeing target located.',effect:g=>g.story.m23TargetLocated=true},'chase-maintain':{msg:'Target remains in sight. Route data captured.',effect:g=>g.story.m23ChaseMaintained=true},identify:{msg:'Chase complete. Target identity confirmed.',effect:g=>{g.story.m23TargetIdentified=true;g.story.evidence=(Number(g.story.evidence)||0)+1;trust(g,'darius','malik',1);}}}},
 M24:{steps:{'search-mark':{msg:'Hidden entrance marker found.',effect:g=>g.story.m24MarkerFound=true},'hidden-entry':{msg:'Concealed entrance discovered.',effect:g=>g.story.m24HiddenEntry=true},'clue-retrieve':{msg:'Clue retrieved from the concealed location.',effect:g=>{g.story.m24ClueRecovered=true;g.story.evidence=(Number(g.story.evidence)||0)+1;}}}},
 M25:{steps:{'office-search':{msg:'Abandoned office searched. The file cache is located.',effect:g=>g.story.m25OfficeSearched=true},'file-recover':{msg:'File recovered before the search closed in.',effect:g=>{g.story.m25FileRecovered=true;g.story.evidence=(Number(g.story.evidence)||0)+1;}},exit:{msg:'Office cleared before the search reached the floor.',effect:g=>{g.story.m25ExitClean=true;g.story.exposure=Math.max(0,(Number(g.story.exposure)||0)-1);trust(g,'amara','darius',1);}}}},
 M26:{steps:{'investment-choose':{msg:'Legitimate investment selected.',effect:g=>g.story.m26InvestmentChosen=true},'investment-fund':{msg:'Clean funds committed to the first investment.',effect:g=>{g.story.m26InvestmentFunded=true;g.story.investmentCapital=(Number(g.story.investmentCapital)||0)+500;}},'return-record':{msg:'First return recorded. The legitimate foothold is established.',effect:g=>{g.story.m26ReturnRecorded=true;g.story.investmentReturn=(Number(g.story.investmentReturn)||0)+75;g.story.legitimateBusinessFooting=true;trust(g,'darius','amara',1);}}}},
 M27:{steps:{'safehouse-unlock':{msg:'Safehouse acquired/unlocked at the workshop location.',effect:g=>g.story.m27SafehouseUnlocked=true},secure:{msg:'Safehouse secured for team use.',effect:g=>{g.story.m27SafehouseSecured=true;g.story.safehouseUnlocked=true;}},'vehicle-store':{msg:'Vehicle stored at the safehouse. The location is now operational.',effect:g=>{g.story.m27VehicleStored=true;const v=findVehicle(g);if(v)v.storedAt='safehouse';trust(g,'malik','darius',2);}}}},
 M28:{steps:{'anomaly-1':{msg:'Accounting anomaly one found.',effect:g=>g.story.m28Anomalies=(Number(g.story.m28Anomalies)||0)+1},'anomaly-2':{msg:'Accounting anomaly two found.',effect:g=>g.story.m28Anomalies=(Number(g.story.m28Anomalies)||0)+1},'anomaly-3':{msg:'Third anomaly found. The accounting pattern is linked.',effect:g=>{g.story.m28Anomalies=(Number(g.story.m28Anomalies)||0)+1;g.story.m28BooksLinked=true;g.story.evidence=(Number(g.story.evidence)||0)+1;trust(g,'amara','darius',2);}}}},
 M29:{steps:{'lead-track':{msg:'Strongest brother lead tracked through Central.',effect:g=>g.story.m29LeadTracked=true},'location-search':{msg:'Next location searched. A trace remains.',effect:g=>g.story.m29LocationSearched=true},'clue-recover':{msg:'Next location clue recovered. The brother trail continues.',effect:g=>{g.story.m29ClueRecovered=true;g.story.brotherTrail=true;g.story.evidence=(Number(g.story.evidence)||0)+1;}}}},
 M30:{steps:{'attack-survive':{msg:'Coordinated attack survived. Keep moving.',effect:g=>{g.story.m30AttackSurvived=true;g.story.exposure=(Number(g.story.exposure)||0)+1;g.story.policePressure=(Number(g.story.policePressure)||0)+1;}},escape:{msg:'Attack zone escaped.',effect:g=>{g.story.m30Escaped=true;g.wanted=Math.max(0,Number(g.wanted||0)-1);}},'evidence-preserve':{msg:'Evidence preserved while the team got clear.',effect:g=>{g.story.m30EvidencePreserved=true;g.story.evidence=(Number(g.story.evidence)||0)+1;trust(g,'malik','darius',2);trust(g,'amara','darius',1);}}}}
};
function G(){return window.gameState||null} function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch03=g.p19.batch03||{};g.p19.batch03.missions=g.p19.batch03.missions||{};g.p19.batch03.qa=g.p19.batch03.qa||{};}
function ms(id){ensure();const g=G();return g.p19.batch03.missions[id]||(g.p19.batch03.missions[id]={actions:{},checkpoints:[],completed:false});}
function save(){window.saveAll?.()} function trust(g,a,b,n){g.p18?.relationships?.[a]?.[b]&&(g.p18.relationships[a][b].trust=Math.min(100,(g.p18.relationships[a][b].trust||0)+n));}
function findVehicle(g){return (g.vehicles||[]).find(v=>v.id==='workshop_getaway_01')||(g.vehicles||[]).find(v=>v.owner==='malik');}
function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.steps?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true;}
function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(G()?.wanted||0)===0;if(x.completed){G().p19.batch03.completedAt=G().p19.batch03.completedAt||{};G().p19.batch03.completedAt[id]=Date.now();}save();}
function qaSnapshot(){ensure();const g=G(),out={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];out[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null};});return out;}
function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}
function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 03 QA <button class="close" onclick="closePanel()">×</button></h3><p>M21-M30 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch03Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};
function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch03.complete){g.p19.batch03.complete=true;g.p19.batch03.completedAt=Date.now();save();window.notice?.('BATCH 03 COMPLETE · M21-M30 production gate passed.')}}
setInterval(observe,500);
window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch03QAButton')){const b=document.createElement('button');b.id='phase19Batch03QAButton';b.textContent='BATCH 03 QA';b.onclick=openQA;q.appendChild(b)}},2000));
})();
