/* 404: NO WAY OUT — PHASE 19 BATCH 07 RUNTIME (M61-M70) */
(function(){'use strict';
const IDS=new Set(['M61','M62','M63','M64','M65','M66','M67','M68','M69','M70']);
const SPECS={
M61:{'delivery-one':{msg:'First delivery completed inside the network window.',effect:g=>g.story.m61One=true},'delivery-two':{msg:'Second delivery completed without breaking the route.',effect:g=>g.story.m61Two=true},'delivery-three':{msg:'All three deliveries completed before the network timed out.',effect:g=>{g.story.m61Three=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M62:{'compare-contacts':{msg:'Contact accounts compared; one contradiction stands out.',effect:g=>g.story.m62Compared=true},'test-lead':{msg:'The suspect lead is tested without burning the useful relationship.',effect:g=>g.story.m62Tested=true},'identify-leak':{msg:'Leak identified and the required relationship preserved.',effect:g=>{g.story.m62Leak=true;g.story.m62RelationshipPreserved=true;}}},
M63:{'locate-drop':{msg:'Timed dead drop located before the rival team arrives.',effect:g=>g.story.m63Located=true},'secure-package':{msg:'Package secured and the drop site remains controlled.',effect:g=>g.story.m63Secured=true},'escape-rivals':{msg:'Rival team missed the package; the drop was recovered cleanly.',effect:g=>{g.story.m63Escaped=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M64:{'log-calls':{msg:'Relevant calls logged in sequence.',effect:g=>g.story.m64Logged=true},'trace-pattern':{msg:'Repeating call pattern traced to a common origin.',effect:g=>g.story.m64Pattern=true},'identify-origin':{msg:'Originating location identified from the call pattern.',effect:g=>{g.story.m64Origin=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M65:{'job-one':{msg:'First linked job completed; the lead is building.',effect:g=>{g.story.m65JobOne=true;g.story.m65Fails=0;}},'job-two':{msg:'Second linked job completed without two consecutive failures.',effect:g=>{g.story.m65JobTwo=true;g.story.m65Fails=0;}},'lock-lead':{msg:'Final linked objective complete; the accumulated lead is secured.',effect:g=>{g.story.m65Lead=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M66:{'review-evidence':{msg:'Evidence distinguishes the three possible approaches.',effect:g=>g.story.m66Reviewed=true},'choose-door':{msg:'Correct approach selected from the evidence.',effect:g=>g.story.m66DoorChosen=true},'enter-site':{msg:'Secure site entered using the evidence-matched route.',effect:g=>{g.story.m66Entered=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M67:{'inspect-business':{msg:'Business checked for legitimate operating viability.',effect:g=>g.story.m67Inspected=true},'acquire-business':{msg:'Business acquisition completed on acceptable terms.',effect:g=>{g.story.m67Acquired=true;g.money=Math.max(0,(+g.money||0)-1000);}},'open-front':{msg:'Business registered and operating as a legitimate front.',effect:g=>{g.story.m67Operating=true;g.story.legitimateFront=true;g.reputation=(+g.reputation||0)+2;}}},
M68:{'audit-payroll':{msg:'Payroll shortfall identified and contained.',effect:g=>g.story.m68Audited=true},'secure-funds':{msg:'Immediate payroll funds secured.',effect:g=>{g.story.m68Funds=true;g.money=(+g.money||0)+500;}},'keep-open':{msg:'Payroll resolved and the business remains open.',effect:g=>{g.story.m68Open=true;g.story.businessOperating=true;}}},
M69:{'review-property':{msg:'Strategic property terms reviewed.',effect:g=>g.story.m69Reviewed=true},'close-purchase':{msg:'Property purchase completed.',effect:g=>{g.story.m69Purchased=true;g.money=Math.max(0,(+g.money||0)-1500);}},'register-ownership':{msg:'Ownership registered and the strategic property is secured.',effect:g=>{g.story.m69Owned=true;g.story.propertyCount=(+g.story.propertyCount||0)+1;}}},
M70:{'select-vehicles':{msg:'Required vehicles selected for the expanded garage.',effect:g=>g.story.m70Selected=true},'store-vehicles':{msg:'Required vehicles stored at Reed Workshop.',effect:g=>{g.story.m70Stored=true;g.story.vehicleStoredCount=Math.max(+g.story.vehicleStoredCount||0,3);}},'unlock-garage':{msg:'Garage tier unlocked and the vehicle base is operational.',effect:g=>{g.story.m70Garage=true;g.story.garageTier=Math.max(+g.story.garageTier||0,2);}}}
};
function G(){return window.gameState||null}function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch07=g.p19.batch07||{};g.p19.batch07.missions=g.p19.batch07.missions||{}}function ms(id){ensure();const g=G();return g.p19.batch07.missions[id]||(g.p19.batch07.missions[id]={actions:{},checkpoints:[],completed:false})}function save(){window.saveAll?.()}function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch07.completedAt=g.p19.batch07.completedAt||{};g.p19.batch07.completedAt[id]=Date.now()}save()}function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 07 QA <button class="close" onclick="closePanel()">×</button></h3><p>M61-M70 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch07Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch07.complete){g.p19.batch07.complete=true;g.p19.batch07.completedAt=Date.now();save();window.notice?.('BATCH 07 COMPLETE · M61-M70 production gate passed.')}}setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch07QAButton')){const b=document.createElement('button');b.id='phase19Batch07QAButton';b.textContent='BATCH 07 QA';b.onclick=openQA;q.appendChild(b)}},2000));})();
