/* 404: NO WAY OUT — PHASE 19 BATCH 05 RUNTIME (M41-M50) */
(function(){'use strict';
const IDS=new Set(['M41','M42','M43','M44','M45','M46','M47','M48','M49','M50']);
const SPECS={
M41:{'observe-regulars':{msg:'Two regulars identified; the cafe pattern is clear.',effect:g=>g.story.m41Regulars=2},'trace-connection':{msg:'A useful connection links the regulars.',effect:g=>g.story.m41Connection=true},'confirm-source':{msg:'Three regulars and one useful connection confirmed.',effect:g=>{g.story.m41Confirmed=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M42:{'hear-problem':{msg:'Both sides are heard before any decision.',effect:g=>g.story.m42Heard=true},deescalate:{msg:'The conflict is contained without raising the temperature.',effect:g=>g.story.m42Deescalated=true},resolve:{msg:'The resident problem is resolved without escalation.',effect:g=>g.story.m42Resolved=true}},
M43:{'meet-contact':{msg:'The neighborhood contact agrees to hear Amara out.',effect:g=>g.story.m43Met=true},'repair-trust':{msg:'Trust improves through a concrete choice, not a speech.',effect:g=>g.story.m43Trust=true},'gain-access':{msg:'Access is granted.',effect:g=>{g.story.m43Access=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M44:{'retrace-memory':{msg:'Amara reconstructs the remembered detail.',effect:g=>g.story.m44Retraced=true},'search-location':{msg:'The remembered location is searched.',effect:g=>g.story.m44Searched=true},'recover-clue':{msg:'The clue is recovered and preserved.',effect:g=>{g.story.m44Clue=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M45:{'follow-first':{msg:'The first rumor source is confirmed.',effect:g=>g.story.m45First=true},'follow-second':{msg:'The second NPC is followed without breaking the chain.',effect:g=>g.story.m45Second=true},'reach-source':{msg:'The rumor source is reached and the chain survives.',effect:g=>{g.story.m45Source=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M46:{'interview-first':{msg:'The first witness account is recorded.',effect:g=>g.story.m46First=true},'interview-second':{msg:'The contradicting account is recorded.',effect:g=>g.story.m46Second=true},'weigh-leads':{msg:'The reliable lead is selected from supporting details.',effect:g=>{g.story.m46Reliable=true;g.story.evidence=(+g.story.evidence||0)+1;}}},
M47:{'read-traffic':{msg:'The gridlock pattern is mapped.',effect:g=>g.story.m47Traffic=true},'route-convoy':{msg:'A viable route keeps the convoy reachable.',effect:g=>g.story.m47Route=true},'reach-destination':{msg:'The destination is reached before the convoy leaves.',effect:g=>g.story.m47Arrived=true}},
M48:{'inspect-vehicle':{msg:'Four damaged tires are confirmed.',effect:g=>g.story.m48Inspected=true},'repair-tires':{msg:'All four tires are repaired.',effect:g=>g.story.m48Repaired=true},'return-vehicle':{msg:'The repaired vehicle is returned.',effect:g=>{g.story.m48Returned=true;g.story.vehicleRepairCount=4;}}},
M49:{'choose-upgrade':{msg:'The workshop upgrade is selected.',effect:g=>g.story.m49UpgradeChosen=true},'install-upgrade':{msg:'The upgrade is installed.',effect:g=>g.story.m49Installed=true},'test-vehicle':{msg:'The vehicle test confirms the new capability.',effect:g=>{g.story.m49Tested=true;g.story.vehicleUpgrade=true;}}},
M50:{'load-item':{msg:'The item is secured for the coastal route.',effect:g=>g.story.m50Loaded=true},'coastal-run':{msg:'The boat completes the coastal route without sinking.',effect:g=>g.story.m50Coastal=true},'dock-delivery':{msg:'The item reaches the dock and is delivered.',effect:g=>{g.story.m50Delivered=true;g.story.evidence=(+g.story.evidence||0)+1;}}}
};
function G(){return window.gameState||null}function ensure(){const g=G();if(!g)return;g.p19=g.p19||{};g.p19.batch05=g.p19.batch05||{};g.p19.batch05.missions=g.p19.batch05.missions||{}}
function ms(id){ensure();const g=G();return g.p19.batch05.missions[id]||(g.p19.batch05.missions[id]={actions:{},checkpoints:[],completed:false})}function save(){window.saveAll?.()}
function handleAction(m,step){if(!IDS.has(m.id))return false;ensure();const spec=SPECS[m.id]?.[step.id];if(!spec)return false;const x=ms(m.id);x.actions[step.id]=(x.actions[step.id]||0)+1;x.checkpoints.push({step:step.id,time:Date.now()});spec.effect?.(G());window.notice?.(spec.msg);window.updateHUD?.();save();window.phase19Advance?.();return true}
function recordCompletion(id,result){if(!IDS.has(id))return;ensure();const g=G(),x=ms(id);x.completed=!!result&&!result.failed;x.result=result||null;x.clean=Number(g?.wanted||0)===0;if(x.completed){g.p19.batch05.completedAt=g.p19.batch05.completedAt||{};g.p19.batch05.completedAt[id]=Date.now()}save()}
function qaSnapshot(){ensure();const g=G(),o={};IDS.forEach(id=>{const x=ms(id),r=g.missionRuntime?.results?.[id];o[id]={completed:!!r&&!r.failed,checkpoints:x.checkpoints.length,actions:x.actions,clean:x.clean??null}});return o}
function batchComplete(){return [...IDS].every(id=>!!G()?.missionRuntime?.results?.[id]&&!G().missionRuntime.results[id].failed)}
function openQA(){const q=qaSnapshot();let h='<h3>PHASE 19 · BATCH 05 QA <button class="close" onclick="closePanel()">×</button></h3><p>M41-M50 runtime acceptance state.</p>';Object.entries(q).forEach(([id,v])=>h+=`<div class="row"><span><b>${id}</b> · ${v.checkpoints} checkpoints</span><b>${v.completed?'PASS':'PENDING'}</b></div>`);h+=`<div class="row"><span>Batch gate</span><b>${batchComplete()?'PASSED':'IN PROGRESS'}</b></div>`;window.panel?.(h)}
window.phase19Batch05Runtime={handleAction,recordCompletion,qaSnapshot,batchComplete,openQA};
function observe(){const g=G();if(!g)return;ensure();IDS.forEach(id=>{const r=g.missionRuntime?.results?.[id],x=ms(id);if(r&&!x.completed)recordCompletion(id,r)});if(batchComplete()&&!g.p19.batch05.complete){g.p19.batch05.complete=true;g.p19.batch05.completedAt=Date.now();save();window.notice?.('BATCH 05 COMPLETE · M41-M50 production gate passed.')}}setInterval(observe,500);window.addEventListener('load',()=>setTimeout(()=>{const q=document.querySelector('.quick-menu');if(q&&!document.getElementById('phase19Batch05QAButton')){const b=document.createElement('button');b.id='phase19Batch05QAButton';b.textContent='BATCH 05 QA';b.onclick=openQA;q.appendChild(b)}},2000));})();
